### ISSUE TITLE
list- variants

### ISSUE THREAD

**Issue by nicferrier** [ScottyB/edebug-x#1]
I'd suggest you have list- variants of all your actual tlm functions - that's what the manual suggests and it's good advice, gives us a very consistent interface.

**Comment by ScottyB** [comment]
Not sure what you mean. Are you referring to the two separate tlm's or the commands available in each?

**Comment by ScottyB** [comment]
Fixed in https://github.com/ScottyB/edebug-x/commit/50625fbfc75210f3014489f504b9bb43faebc75f.
